version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: alx_travel_db
      MYSQL_USER: alx_user
      MYSQL_PASSWORD: strongpass
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    environment:
      - DEBUG=True
      - SECRET_KEY=your-secret-key-change-me
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - DB_ENGINE=mysql
      - DB_NAME=alx_travel_db
      - DB_USER=alx_user
      - DB_PASSWORD=strongpass
      - DB_HOST=db
      - DB_PORT=3306
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  celery:
    build: .
    restart: always
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - SECRET_KEY=your-secret-key-change-me
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - DB_ENGINE=mysql
      - DB_NAME=alx_travel_db
      - DB_USER=alx_user
      - DB_PASSWORD=strongpass
      - DB_HOST=db
      - DB_PORT=3306
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
    command: celery -A alx_travel_app worker --loglevel=info

volumes:
  mysql_data:
  static_volume:
